### ISSUE TITLE
Transfer from raw C bindings to STD calls

### ISSUE THREAD

**Issue by Meziu** [Meziu/rust3ds-network-example#1]
First working version (a bare translation of the devkitpro network example).
@AzureMarker, you may be interested in this :smile:

**Comment by AzureMarker** [comment]
Thanks! I'm having an issue where `gethostid` is not defined. Maybe the libc repo is missing a commit?

I saw there was some concern about using libctru in Rust's std. Is that still a concern, or how are you planning on integrating it?

**Comment by Meziu** [comment]
Ctru in std is a concern, that's why ctru-rs has all of the weird link layers. As for libc: i lost all of my work there. My pc after a reboot won't work anymore, so I'm doing a full reinstall with a backup. Libc has been lost too, though it was only a couple of changes. By tomorrow I should be able to reimplement them...

**Comment by Meziu** [comment]
@AzureMarker should be fixed now, installed OpenSUSE instead of Ubuntu for fun since the install was screwed anyways.

**Comment by AzureMarker** [comment]
Thanks! I got it running on my 3ds. For some reason Citra doesn't run it quite right:
![image](https://user-images.githubusercontent.com/4417660/147515764-6a37848d-fb57-492f-a3d2-488da6d6314b.png)

**Comment by Meziu** [comment]
Maybe you have to activate networking on citra, or maybe citra makes a "container" to run the emulated software, so it can't connect to the internet. Still, emulation is not a priority, nor really related to this project.

**Comment by AzureMarker** [comment]
By the way I have some progress on getting std TcpListener to work. I can open a draft PR against your rustc repo tomorrow. It's not working yet, but maybe it will help.

**Comment by Meziu** [comment]
I've got the TcpListener to bind. It's still crashing, and i guess the problem is in the accept. No problem, if you have any info I don't, it'll only make the process faster.

**Comment by AzureMarker** [comment]
Opened https://github.com/Meziu/rust-horizon/pull/1

**Comment by AzureMarker** [comment]
Here's an example of using std networking types successfully:
https://github.com/AzureMarker/n3ds-controller/tree/cd32303a96081aa253d89167696ee6787581bfd0

**Comment by Meziu** [comment]
> Here's an example of using std networking types successfully (needs the above PR to work): https://github.com/AzureMarker/n3ds-controller/blob/f25ed8aebc7b4ad86a1787597d76bdca42d9d17d/src/main.rs

To me this just crashes once the request is made. Doesn't it to you?

**Comment by Meziu** [comment]
Ok, nope, it works. I made a change to libc (sockaddr was an incomplete array, not a pointer to an array, i hate C definitions). Now writing to sockaddr should be easier.

**Comment by Meziu** [comment]
Aight I'm stupid. Cargo holds the cache for the git repos, and my updated libc hadn't been fetched. `cargo update` fixed it. I guess my example could work too then.
